export const primaryColors = {
    priDefault : '#2C4B9C',
    priLight: '#5072A8',
    priLighter: '#7598BC',
    priExtraLight: '#9EBFD6',
    priUltraLight : '#C7E4F1',
    priDark : '#103779',
    priDarker : '#002A5C',
    priExtraDark : '#002443',
    priUltraDark : '#001C2E',
}

export const secondaryColors = {
    secDefault: '#91D1F3',
    secLight: '#B8E7FC',
    secLighter: '#D4F5FF',
    secExtraLight: '#E6FDFF',
    secUltraLight: '#F0FFFF',
    secDark: '#58B3DD',
    secDarker: '#2195C3',
    secExtraDark: '#027DA6',
    secUltraDark: '#006A87',
}

export const neutralColors={
    white: '#FFFFFF',
    greyUltraLight: '#DCE2EB',
    greyExtraLight: '#BCC6D7',
    greyLighter: '#8392AB',
    greyLight: '#526480',
    grey: '#2C415C',
    greyDark: '#112941',
    greyDarker: '#001C2E',
    greyExtraDark: '#00161A',
    greyUltraDark: '#000B0A',
    black: '#000000',
}

export const semanticColors = {
    green: '#3DD43D',
    greenLight: '#55E262',
    greenLighter: '#72ED88',
    greenExtraLight: '#94F5AF',
    greenUltraLight: '#B9FAD2',
    greenDark: '#32C546',
    greenDarker: '#29B14E',
    greenExtraDark: '#229954',
    greenUltraDark: '#1C7D52',
    red: '#FF5858',
    redLight: '#FF7777',
    redLighter: '#FF9999',
    redExtraLight: '#FFBFBF',
    redUltraLight: '#FFD2D2',
    redDark: '#EE4646',
    redDarker: '#DA3838',
    redExtraDark: '#C12D2D',
    redUltraDark: '#A32525',
    yellow: '#F3E44A',
    yellowLight: '#F5E663',
    yellowLighter: '#F7E880',
    yellowExtraLight: '#F9EDA4',
    yellowUltraLight: '#FBF3CB',
    yellowDark: '#F5DE44',
    yellowDarker: '#FBD741',
    yellowExtraDark: '#FAD141',
    yellowUltraDark: '#FDCA43',
    orange: '#FBAE50',
    orangeLight: '#FCB468',
    orangeLighter: '#FCBE86',
    orangeExtraLight: '#FDCDA8',
    orangeUltraLight: '#FEE1CE',
    orangeDark: '#FC9E48',
    orangeDarker: '#FD8F44',
    orangeExtraDark: '#FD8143',
    orangeUltraDark: '#FE7445',
    purple: '#9C2BAB',
    purpleLight: '#AD3CB2',
    purpleLighter: '#B852B6',
    purpleExtraLight: '#BD70B7',
    purpleUltraLight: '#C092BA',
    purpleDark: '#9B1BA5',
    purpleDarker: '#98149D',
    purpleExtraDark: '#920C92',
    purpleUltraDark: '#870683',
}

export const nightPrimary = {
    nightPri:'#9EBFD6',
    nightPriLight: '#ABC8DD',
    nightPriLighter: '#BDD2E4',
    nightPriExtraLight: '#CDDDEB',
    nightPriUltraLight: '#E1E9F1',
    nightPriDark: '#A0C1DE',
    nightPriDarker: '#A3C2E6',
    nightPriExtraDark: '#A7C3EF',
    nightPriUltraDark: '#ADC3F7',
}

export const nightSecondary= {
    nightSec: '#91D1F3',
    nightSecLight: '#B8E7FC',
    nightSecLighter: '#D4F5FF',
    nightSecDark: '#58B3DD',
    nightSecDarker: '#37BCDE',
    nightSecExtraLight:'#E6FDFF',
    nightSecUltraLight: '#F0FFFF',
    nightSecExtraDark:'#26D1E2',
    nightSecUltraDark: '#1AEAE5',
}

export const nightNeutral ={
    nightGrey: '#DCE2EB',
    nightGreyLight: '#E4EBF2',
    nightGreyLighter: '#ECF2F6',
    nightGreyDark: '#D5DDE4',
    nightGreyDarker: '#CDD5DA',
    nightWhite: '#FFFFFF',
    nightGreyExtraLight: '#F2F8FA',
    nightGreyUltraLight: '#F8FCFD',
    nightGreyExtraDark: '#C3CCCF',
    nightGreyUltraDark: '#B7C0C2',
}

export const nightSemantic = {
    nightGreen: '#3DD43D',
    nightGreenLight: '#55E262',
    nightGreenLighter: '#72ED88',
    nightGreenDark: '#32C546',
    nightGreenDarker: '#29B14E',
    nightGreenExtraLight: '#94F5AF',
    nightGreenUltraLight: '#B9FAD2',
    nightGreenExtraDark: '#3CAF56',
    nightGreenUltraDark: '#4EAF5F',

    nightRed: '#FF7777',
    nightRedLight: '#FF9999',
    nightRedLighter: '#FFBFBF',
    nightRedDark: '#FF7067',
    nightRedDarker: '#FF6952',
    nightRedExtraLight: '#FFD2D2',
    nightRedUltraLight: '#FFD7D7',
    nightRedExtraDark: '#FF643A',
    nightRedUltraDark: '#FF6320',

    nightYellow: '#F3E44A',
    nightYellowLight: '#F5E663',
    nightYellowLighter: '#F7E880',
    nightYellowDark: '#F5DE44',
    nightYellowDarker: '#F8D741',
    nightYellowExtraLight: '#F9EDA4',
    nightYellowUltraLight: '#FBF3CB',
    nightYellowExtraDark: '#FAD141',
    nightYellowUltraDark: '#FDCA43',
    
    nightOrange: '#FBAE50',
    nightOrangeLight: '#FCB468',
    nightOrangeLighter: '#FCBE86',
    nightOrangeDark: '#FC9E48',
    nightOrangeDarker: '#FD8F44',
    nightOrangeExtraLight: '#FDCDA8',
    nightOrangeUltraLight: '#FEE1CE',
    nightOrangeExtraDark: '#FD8143',
    nightOrangeUltraDark: '#FE7445',

    nightPurple: '#C092BA',
    nightPurpleLight: '#CB9FC6',
    nightPurpleLighter: '#D5ABD3',
    nightPurpleDark: '#D08ECC',
    nightPurpleDarker: '#DF86E0',
    nightPurpleExtraLight: '#E0B4DF',
    nightPurpleUltraLight: '#E9BCEA',
    nightPurpleExtraDark: '#E67AEF',
    nightPurpleUltraDark: '#E96DFF',

}



export const Colors= {
    ...primaryColors,
    ...secondaryColors,
    ...neutralColors,
    ...semanticColors,
    ...nightPrimary,
    ...nightSecondary,
    ...nightSemantic,
    ...nightNeutral,
}

